---
name: Go
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go:
        - "1.10"
        - "1.11"
        - "1.12"
        - "1.13"
        - "1.14"
        - "1.15"
        - "1.16"
        - "1.17"
        - "1.18"
        - "1.19"
    env:
      GOPATH: ${{ github.workspace }}/go
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/go/src/github.com/conduitio/yaml/v3
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
        stable: false
    - run: go version
    - run: go get -t ./...
      working-directory: ${{ github.workspace }}/go/src/github.com/conduitio/yaml/v3
    - run: go test .
      working-directory: ${{ github.workspace }}/go/src/github.com/conduitio/yaml/v3
